name: Unity Error Check
on:
  workflow_dispatch: {}
jobs:
  Check:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        clean: false
        lfs: false
    - name: OpenUnity
      run: ${{ secrets.UNITY_EDITOR_PATH }} -quit -batchmode -projectPath ${{ secrets.UNITY_PROJECT_PATH }}

    - name: PostMessage
      if: ${{ failure() }}
      run:
        Invoke-WebRequest -Headers @{"Content-Type"="application/json"} -Method Post -Body "{`"content`":`"Compile Error`"}" ${{ secrets.DISCORD_WEBHOOK_URL }}